export enum DATATYPES {
    BIGINT = 'bigint',
    BIT = 'bit',
    BLOB = 'blob',
    CHAR = 'char',
    CLOB = 'clob',
    DATE = 'date',
    DATETIME = 'datetime',
    DECIMAL = 'decimal',
    DOUBLE = 'double',
    FLOAT = 'float',
    INT = 'int',
    JSON = 'json',
    MONEY = 'money',
    NCHAR = 'nchar',
    NULL = 'null',
    SMALLDATETIME = 'smalldatetime',
    SMALLINT = 'smallint',
    SMALLMONEY = 'smallmoney',
    TIME = 'time',
    TIMESTAMP = 'timestamp',
    TINYINT = 'tinyint',
    UNIQUEIDENTIFIER = 'uniqueidentifier'
}